baseURL = "https://4fofa.netlify.app/"
languageCode = "en-us"
theme = "ananke"
defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

# [services.googleAnalytics]
# id = ''

[pagination]
pagerSize = 10 # number of blog entries per page


[languages.en]
contentDir = "content"
languageCode = 'en-US'
weight = 1
title = "Forth on Fourth Avenue (FOFA)"




# resourceDir = "../resources"





[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
summaryLength = 70 # Number of words in the summary
text_color = ""
show_recent_posts = false
custom_css = ["assets/css/custom.css"]
favicon = ""
site_logo = "images/FOFA-logo.avif"
author = "Forth on Fourth Avenue"
description = "Advocating for community improvements along Fourth Avenue."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-center"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3

[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "bluesky",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "facebook",
  "bluesky",
  "linkedin"
]

[params.ananke.social.facebook]
username = "patrick.kollitsch"
# profilelink = "https://www.facebook.com/patrick.kollitsch"

[params.ananke.social.linkedin]
username = "patrickkollitsch"

[params.ananke.social.bluesky]
username = "kollitsch.dev"

# Main menu
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "resources"
  name = "Resources"
  url = "/resources/"
  weight = 3

[[menu.main]]
  identifier = "news"
  name = "News"
  url = "/news/"
  weight = 4

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 5
  